/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Mail.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Mail
 #	author : miyako
 #	2025/11/18
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Mail.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Mail
            
			case 1 :
				CREATE_EMAIL_DRAFT(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -



static bool _object_to_path(PA_ObjectRef f, std::string& path, int type) {
 
    if(f != NULL) {
        C_TEXT pp;
        pp.setUTF8String((const uint8_t *)"platformPath", 12);
        PA_Unistring PLATFORMPATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());
        
        if(PA_GetObjectPropertyType(f, &PLATFORMPATH) == eVK_Unistring) {
            
            PA_Variable p = PA_GetObjectProperty(f, &PLATFORMPATH);
            PA_Variable    cbparams[2];
            cbparams[0] = PA_CreateVariable(eVK_Unistring);
            cbparams[1] = PA_CreateVariable(eVK_Longint);
            PA_Unistring platformPath = PA_GetStringVariable(p);
            PA_SetStringVariable(&cbparams[0], &platformPath);
            PA_SetLongintVariable(&cbparams[1], 1/*fk platform path*/);
            PA_Variable folder = PA_ExecuteCommandByID(type, cbparams, 2);
            
#if VERSIONMAC
            pp.setUTF8String((const uint8_t *)"path", 4);
            PA_Unistring PATH = PA_CreateUnistring((PA_Unichar *)pp.getUTF16StringPtr());
            PA_Variable _p = PA_GetObjectProperty(PA_GetObjectVariable(folder), &PATH);
            platformPath = PA_GetStringVariable(_p);
#endif
            C_TEXT t;
            t.setUTF16String(&platformPath);
            CUTF8String u8;
            t.copyUTF8String(&u8);
            path = std::string((const char *)u8.c_str(), u8.size());
            
            PA_ClearVariable(&cbparams[0]);
            PA_ClearVariable(&cbparams[1]);
            PA_DisposeUnistring(&PLATFORMPATH);
#if VERSIONMAC
            PA_DisposeUnistring(&PATH);
            PA_ClearVariable(&_p);//see .h of PA_GetObjectProperty
#endif
            PA_ClearVariable(&p);//see .h of PA_GetObjectProperty
            PA_ClearVariable(&folder);
            
            return true;
        }
        
        PA_DisposeUnistring(&PLATFORMPATH);
    }
    
    return false;
}

static bool file_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1566 /*4D.File*/);
}

static bool folder_object_to_path(PA_ObjectRef f, std::string& path) {
    
    return _object_to_path(f, path, 1567 /*4D.Folder*/);
}

static PA_ObjectRef path_to_folder_object(std::string& m) {
    
    PA_Variable    cbparams[2];
    cbparams[0] = PA_CreateVariable(eVK_Unistring);
    cbparams[1] = PA_CreateVariable(eVK_Longint);
    
    C_TEXT t;
    t.setUTF8String((const uint8_t *)m.c_str(), (uint32_t)m.length());
    PA_Unistring path = PA_CreateUnistring((PA_Unichar *)t.getUTF16StringPtr());
    
    PA_SetStringVariable(&cbparams[0], &path);
    PA_SetLongintVariable(&cbparams[1], 1/*fk platform path*/);
    PA_Variable folder = PA_ExecuteCommandByID(1567 /*4D.Folder*/, cbparams, 2);
    PA_ClearVariable(&cbparams[0]);
    PA_ClearVariable(&cbparams[1]);
    PA_DisposeUnistring(&path);

    // NOTE: `folder` is intentionally NOT cleared here (unlike in _object_to_path)
    // because the PA_ObjectRef this function returns is owned by it; clearing
    // the variable before returning could invalidate the returned reference.
    // This function is currently unused (dead code) — remove it if it stays that way.
    return PA_GetObjectVariable(folder);
}

#pragma mark -



static void __CREATE_EMAIL_DRAFT__(NSDictionary *dict) {
    
    NSSharingService *service =
        [NSSharingService sharingServiceNamed:NSSharingServiceNameComposeEmail];

    /*
     NSString               Plain text body (Mail sanitizes)
     NSAttributedString     Rich text / HTML, preserved exactly
     NSURL (file)           Adds as attachment
     NSImage                Converts to file and attaches inline
     NSData                 Depends on UTI; may attach or ignore
     NSPasteboardWriting    Advanced custom items
     */
    
    NSString *subject = [dict objectForKey:@"subject"];
    if(subject) {
        service.subject = subject;
    }
    NSArray *recipients = [dict objectForKey:@"recipients"];
    if(recipients) {
        service.recipients = recipients;
    }
    
    NSMutableArray *items = [[NSMutableArray alloc]init];
    
    // HTML -> NSAttributedString conversion is done here (main thread) rather than
    // in CREATE_EMAIL_DRAFT, because Apple's HTML import for NSAttributedString
    // requires the main thread and can otherwise misbehave, hang, or return nil
    // when called from a background/worker thread (this command is threadSafe).
    NSString *html = [dict objectForKey:@"htmlBody"];
    if(html) {
        NSAttributedString *htmlBody = [[NSAttributedString alloc]
            initWithData:[html dataUsingEncoding:NSUTF8StringEncoding]
            options:@{NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType}
            documentAttributes:nil
            error:nil];
        if(htmlBody) {
            [items addObject:htmlBody];
        }
        [htmlBody release];
    }
    NSString *textBody = [dict objectForKey:@"textBody"];
    if(textBody) {
        [items addObject:textBody];
    }
    NSArray *attachments = [dict objectForKey:@"attachments"];
    if(attachments) {
        [items addObjectsFromArray:attachments];
    }

    [service performWithItems:items];

    [items release];
}

static void CREATE_EMAIL_DRAFT(PA_PluginParameters params) {

    PA_ObjectRef options = PA_GetObjectParameter(params, 1);
    if(options) {
        
        NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];
        
        CUTF8String _textBody, _htmlBody, _subject;
        if(ob_get_a(options, L"htmlBody", &_htmlBody)) {
            // Raw HTML text is handed across as-is; it is converted to an
            // NSAttributedString on the main thread in __CREATE_EMAIL_DRAFT__
            // (see note there for why).
            NSString *html = [[NSString alloc]initWithUTF8String:(const char *)_htmlBody.c_str()];
            if(html) {
                [dict setObject:html forKey:@"htmlBody"];
            }
            [html release];
        }
        
        if(ob_get_a(options, L"textBody", &_textBody)) {
            NSString *textBody = [[NSString alloc]initWithUTF8String:(const char *)_textBody.c_str()];
            if(textBody) {
                [dict setObject:textBody forKey:@"textBody"];
            }
            [textBody release];
        }

        if(ob_get_a(options, L"subject", &_subject)) {
            NSString *subject = [[NSString alloc]initWithUTF8String:(const char *)_subject.c_str()];
            if(subject) {
                [dict setObject:subject forKey:@"subject"];
            }
            [subject release];
        }

        PA_CollectionRef _attachments = ob_get_c(options, L"attachments");
        if(_attachments) {
            NSMutableArray *attachments = [[NSMutableArray alloc]init];
            for (PA_long32 i = 0; i < PA_GetCollectionLength(_attachments); ++i) {
                PA_Variable v = PA_GetCollectionElement(_attachments, i);
                if(PA_GetVariableKind(v) == eVK_Object) {
                    PA_ObjectRef o = PA_GetObjectVariable(v);
                    std::string path;
                    if(file_object_to_path(o, path)) {
                        NSString *a = [[NSString alloc]initWithUTF8String:path.c_str()];
                        if(a) {
                            NSURL *u = [[NSURL alloc]initFileURLWithPath:a];
                            if(u) {
                                [attachments addObject:u];
                            }
                            [u release];
                        }
                        [a release];
                    }
                }
            }
            [dict setObject:attachments forKey:@"attachments"];
            [attachments release];
        }
        
        PA_CollectionRef _recipients = ob_get_c(options, L"recipients");
        if(_recipients) {
            NSMutableArray *recipients = [[NSMutableArray alloc]init];
            for (PA_long32 i = 0; i < PA_GetCollectionLength(_recipients); ++i) {
                PA_Variable v = PA_GetCollectionElement(_recipients, i);
                if(PA_GetVariableKind(v) == eVK_Unistring) {
                    PA_Unistring s = PA_GetStringVariable(v);
                    C_TEXT t;
                    t.setUTF16String(&s);
                    NSString *r = t.copyUTF16String();
                    if(r) {
                        [recipients addObject:r];
                    }
                    [r release];
                }
            }
            // setObject:/release moved OUTSIDE the for-loop (previously nested one
            // brace too shallow, which released `recipients` after the 1st element
            // and then reused it on the 2nd -> use-after-free / crash with 2+ recipients,
            // and leaked it entirely with 0 recipients).
            [dict setObject:recipients forKey:@"recipients"];
            [recipients release];
        }

        PA_RunInMainProcess(
                            (PA_RunInMainProcessProcPtr)__CREATE_EMAIL_DRAFT__,
                            (void *)dict);
        
        [dict release];
    }
}

