/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Mail.h
 #	source generated by 4D Plugin Wizard
 #	Project : Mail
 #	author : miyako
 #	2025/11/18
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MAIL_H
#define PLUGIN_MAIL_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#import <Cocoa/Cocoa.h>

#include <sstream>
#include <iostream>

#include "C_TEXT.h"

static void CREATE_EMAIL_DRAFT(PA_PluginParameters params);

#endif /* PLUGIN_MAIL_H */
